<?php

	/**
	 * File Creation Date: 2012-04-12T06:39:59+02:00

	 * This file was autogenerated by PHP-Array-Configurator
	 * @link https://github.com/Philzen/Php-Array-Configurator
	 *
	 * !!! DO NOT MODIFY THIS FILE BY HAND (not unless you know exactly what you are doing and are prepared for desaster) !!!
	 **/
	 
	return array(
		'production' => array(
			'bla' => 'blub',
			'foo' => 'foovalue',
			'bar' => 'barvalue',
			'urls' => array(
				'one' => 'http://example.com',
				'two' => 'http://example2.com',
			),
			'email' => array(
				'hghs@idhwi.de', 'dueuihued@ihdiw.com'
			),
		),
	);